eval_backend: VLMEvalKit
eval_config:
  model: 
    - type: qwen-vl-chat   # swift model type
      name: CustomAPIModel # Don't change, must be CustomAPIModel for swift deploy evaluation
      api_base: http://localhost:8000/v1/chat/completions # swfit deploy model api
      key: EMPTY
      temperature: 0.0
  data:
    - SEEDBench_IMG
    - ChartQA_TEST
  mode: all
  limit: 20
  rerun: true
  work_dir: output
  nproc: 1
  # judge model server config
  OPENAI_API_KEY: EMPTY
  OPENAI_API_BASE: http://localhost:8866/v1/chat/completions # judge model api
  LOCAL_LLM: qwen2-7b-instruct                               # judge model type