task_name: task_chatglm_mgsm

task_chatglm_mgsm:
  id: task_chatglm_mgsm_ver_0
  predictor:
    ref: evals.predictors.local_inference_predictor:LocalInferencePredictor
    args:
      model: chatglm2-6b
      local_model:
        model_path: /mnt/workspace/models/chatglm2-6b
      temperature: 0
  evaluator:
    ref: evals.evaluator.math_eval:MathEvaluate
    args:
      metrics: ['math_accuracy']
      md_level: 2
