task_name: task_moss_exam

task_moss_exam:
    id: task_moss_exam_dev_v0
    predictor:
        ref: evals.predictors.moss_predictor:MossPredictor
        args:
            mode: remote
            model: moss_dev5
            max_length: 500
            top_k: 15
    scoring_model:
        ref: evals.scoring_models.generation:GenerationEvaluate
        args:
            metrics: [ bleu, rouge ]
