task_name: task_qwen_common_generation

task_qwen_common_generation:
    id: task_qwen_common_generation_ver_0
    evaluator:
        ref: llmuses.evaluator.generation:CommonGenerationEvaluate
        args:
            metrics: ['rouge']
            md_level: 2
            report_metric_key: 'rouge-l-f'
